// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiendaProductosAPI.Data;

#nullable disable

namespace TiendaProductosAPI.Migrations
{
    [DbContext(typeof(TiendaDbContext))]
    [Migration("20260824020617_CreacionInicial")]
    partial class CreacionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TiendaProductosAPI.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Laptop HP 15",
                            Precio = 5499.99m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Mouse inalámbrico",
                            Precio = 129.50m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Teclado mecánico",
                            Precio = 389.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Monitor 24 pulgadas",
                            Precio = 1899.90m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Audífonos Bluetooth",
                            Precio = 249.75m,
                            Stock = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
